version: "3"

services:

  mailcatcher:
    image: dockage/mailcatcher
    ports: [1080,1025]
    labels:
      com.symfony.server.service-prefix: 'MAILER'

  rabbitmq:
    image: rabbitmq:3-management
    ports: [15672,5672]
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
